services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    restart: always
    depends_on: [zookeeper]
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

  schema-registry:
    image: confluentinc/cp-schema-registry:7.4.0
    restart: always
    depends_on: [kafka]
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  # 3) Microservices (pull from Docker Hub)
  subscription-service:
    image: "${DOCKERHUB_USERNAME}/subscription-service:latest"
    restart: always
    depends_on: [kafka, schema-registry]
    ports:
      - "${SUB_SERVICE_PORT}:4000"
    environment:
      SPRING_DATASOURCE_URL: "${SUB_DB_URL}"
      SPRING_DATASOURCE_USERNAME: "${SUB_DB_USER}"
      SPRING_DATASOURCE_PASSWORD: "${SUB_DB_PASS}"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "${KAFKA_BOOTSTRAP_SERVERS}"
      SPRING_KAFKA_PRODUCER_PROPERTIES_SCHEMA_REGISTRY_URL: "${SCHEMA_REGISTRY_URL}"
      SERVER_PORT: 4000

  auth-service:
    image: "${DOCKERHUB_USERNAME}/auth-service:latest"
    restart: always
    ports:
      - "${AUTH_SERVICE_PORT}:4005"
    environment:
      SPRING_DATASOURCE_URL: "${AUTH_DB_URL}"
      SPRING_DATASOURCE_USERNAME: "${AUTH_DB_USER}"
      SPRING_DATASOURCE_PASSWORD: "${AUTH_DB_PASS}"
      SERVER_PORT: 4005

  api-gateway:
    image: "${DOCKERHUB_USERNAME}/api-gateway:latest"
    restart: always
    depends_on: [auth-service, subscription-service]
    ports:
      - "${API_GATEWAY_PORT}:4004"
    environment:
      SERVER_PORT: 4004

  reminder-service:
    image: "${DOCKERHUB_USERNAME}/reminder-service:latest"
    restart: always
    depends_on: [subscription-service, kafka, schema-registry]
    ports:
      - "${REMINDER_SERVICE_PORT}:4002"
    environment:
      SPRING_DATASOURCE_URL: "${SUB_DB_URL}"
      SPRING_DATASOURCE_USERNAME: "${SUB_DB_USER}"
      SPRING_DATASOURCE_PASSWORD: "${SUB_DB_PASS}"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "${KAFKA_BOOTSTRAP_SERVERS}"
      SPRING_KAFKA_PRODUCER_PROPERTIES_SCHEMA_REGISTRY_URL: "${SCHEMA_REGISTRY_URL}"
      SERVER_PORT: 4002

volumes:
  subscription_data:
  auth_data:
