name: CI/CD → Docker Hub & EC2

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build-and-push:
    name: Build JARs & Push Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" \
            | docker login --username "${{ env.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build & Push all services
        run: |
          for svc in subscription-service auth-service api-gateway reminder-service; do
            docker build -t ${{ env.DOCKERHUB_USERNAME }}/$svc:latest ./$svc
            docker push ${{ env.DOCKERHUB_USERNAME }}/$svc:latest
          done

  deploy:
    name: SSH-Deploy to EC2
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: SSH Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/subscription-tracker
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d
